-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/cognate_pages (
  cgpa_site BIGINT NOT NULL,
  cgpa_namespace INTEGER NOT NULL,
  cgpa_title BIGINT NOT NULL,
  PRIMARY KEY(
    cgpa_title, cgpa_namespace, cgpa_site
  )
);


CREATE TABLE /*_*/cognate_sites (
  cgsi_key BIGINT NOT NULL,
  cgsi_dbname BLOB NOT NULL,
  cgsi_interwiki BLOB NOT NULL,
  PRIMARY KEY(cgsi_key)
);


CREATE TABLE /*_*/cognate_titles (
  cgti_raw_key BIGINT NOT NULL,
  cgti_raw BLOB NOT NULL,
  cgti_normalized_key BIGINT NOT NULL,
  PRIMARY KEY(cgti_raw_key)
);

CREATE INDEX cgti_normalized_keys ON /*_*/cognate_titles (cgti_normalized_key);
