-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/cognate_pages (
  cgpa_site BIGINT NOT NULL,
  cgpa_namespace INT NOT NULL,
  cgpa_title BIGINT NOT NULL,
  PRIMARY KEY(
    cgpa_title, cgpa_namespace, cgpa_site
  )
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/cognate_sites (
  cgsi_key BIGINT NOT NULL,
  cgsi_dbname VARBINARY(32) NOT NULL,
  cgsi_interwiki VARBINARY(32) NOT NULL,
  PRIMARY KEY(cgsi_key)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/cognate_titles (
  cgti_raw_key BIGINT NOT NULL,
  cgti_raw VARBINARY(255) NOT NULL,
  cgti_normalized_key BIGINT NOT NULL,
  INDEX cgti_normalized_keys (cgti_normalized_key),
  PRIMARY KEY(cgti_raw_key)
) /*$wgDBTableOptions*/;
